name: 'Terraform'

#on:
#  push:
#    branches: [ "main" ]
#  pull_request:

  on:
    workflow_dispatch:
      inputs:
        env:
          description: 'Environment to deploy to'
          required: true
          default: 'production'
          type: choice
          options: ['staging','production']
    
permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
#    environment: production   #### Ignore the error in VS it's working based on my testing ( Peter 19 Oct 2024)

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      env:
        GOOGLE_CREDENTIALS: ${{ SECRETS.GCP_PROJECT_IAM_KEY}}

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt -check
      env:
           GOOGLE_CREDENTIALS: ${{ SECRETS.GCP_PROJECT_IAM_KEY}}  
    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan -input=false
      env:
        GOOGLE_CREDENTIALS: ${{ SECRETS.GCP_PROJECT_IAM_KEY}}

      # On push to "main", build or change infrastructure according to Terraform configuration files
      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve -input=false
      timeout-minutes: 3
      env: 
        GOOGLE_CREDENTIALS: ${{ SECRETS.GCP_PROJECT_IAM_KEY }}

#    - id: 'compute-ssh'
#      uses: 'google-github-actions/ssh-compute@v1'
#      with:
#        instance_name: 'database-instance'
#        zone: 'europe-west2-a'
#        ssh_private_key: '${{ secrets.GCP_SSH_PRIVATE_KEY }}'
#        command: 'echo Hello world'

